name: Build and Push Docker image using Buildpacks

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn clean package

      - name: Install Pack CLI
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.33.1/pack-v0.33.1-linux.tgz" | tar -xz
          sudo mv pack /usr/local/bin/

      - name: Build image with Buildpacks
        run: |
          pack build registry.local:5000/demo-api:0.0.1-SNAPSHOT \
            --path . \
            --builder paketobuildpacks/builder:base \
            --env BP_JVM_VERSION=17

      - name: Push image to local registry
        run: docker push registry.local:5000/demo-api:0.0.1-SNAPSHOT
